### ISSUE TITLE
Technology ideas

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#1]
- Express with Typescript (or using a framework like [Feathers](https://feathersjs.com))
- Cucumber
- Mongo

**Comment by bineetNaidu** [comment]
* Electron with React Js.

**Comment by BOLT04** [comment]
@bineetNaidu those are good suggestions, but I think this project would more of a back-end API. So I agree with choosing Express + node.js + Typescript + MongoDB 😃

**Comment by bineetNaidu** [comment]
> @bineetNaidu those are good suggestions, but I think this project would more of a back-end API. So I agree with choosing Express + node.js + Typescript + MongoDB 
> The reason I'd choose express is that I think more contributors would know it, but I'm down to learning something new. Challenges are always welcome

Yes i agree with you if we are goin with backend  then for sure that i will be goin with Express + node.js + Typescript + MongoDB 
as i am familiar with the stack , from the past 2 to 3 months i have build a lots projects based with this stack. 

Yes i am really excited and looking forward to contribute and work on to this project.

**Comment by BOLT04** [comment]
awesome @bineetNaidu, it's great to hear that 😃

**Comment by vivek80801** [comment]
- Gatsby 
- nextjs
- ecommarce website with nextjs 
-  chat app with login functionality
- MERN stack with typescript

**Comment by BOLT04** [comment]
Hi @vivek80801 😃, you have some cool ideas there. However for this project we are looking to build a RESTful API to serve EddieBot and EddieBotUI (and any other project we want actually 😅). Since both of those need to access data in a database, this API would be the data access layer... kinda 😅. At least for now that would be the primary goal.

Perhaps we can start other projects using the options you mentioned, so if you want, [raise an issue](https://github.com/EddieJaoudeCommunity/support/issues) on the support repo with your ideas to start the conversation and to get more feedback from others 👍

**Comment by vivek80801** [comment]
@BOLT04  

Ok.

**Comment by eddiejaoude** [comment]
Going to close this, looks like we are going with NestJS
