### ISSUE TITLE
Using namespace for separate of data

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#137]
I was thinking, the `namespace` could be set in the service? this could be the name of the Discord server id - then it would help us easily separate the data between servers

Currently it is set in the module

```ts
AstraModule.forFeature({ namespace: 'eddiehub', collection: 'discord' }),
```

What do you think?

**Comment by Cahllagerfeld** [comment]
First of all I think thats possible, but with a little refactoring I guess.
My first question is: Is it meant to be a `saas`-Solution where the api is used for many bots as Frontend, or can we say every bot has its own api?

Here are my thoughts on that: 

- I think we cant use the Astra-Service in that scenario, because it needs the `forFeature`-Settings injected when starting the application.
- When settings the `namespace` dynamically for every-request we probably need to configure the client (which does the actual request) for every request on the fly when an actual request comes in. We should check perforance in that regard
- I need to check if we can use the Nest.js-Astra-Coremodule, because I think nothing will change on the base-client with the url and stuff.
   - If we can use the Astra-Core-Module we probably dont have to do a huge refactoring
   - In case we cant we probably need to think of another solution for that.

**Comment by eddiejaoude** [comment]
Thank you for the quick response 👍 

There are people who would like to use EddieBot where they can enable/disable certain features and configure those features, so I think it would be to go down that route from the beginning to be able to support multiple Discord servers.

> I think we cant use the Astra-Service in that scenario, because it needs the forFeature-Settings injected when starting the application.

Is there another way we can use the nestjs service so we can update what we send to it? The Astra client accepts the namespace, could we pass the name space in the service instead of the module?

```ts
astraClient.namespace("app").collection("users");
```

> When settings the namespace dynamically for every-request we probably need to configure the client (which does the actual request) for every request on the fly when an actual request comes in. We should check perforance in that regard

I think it will keep each one available in memory, so I don't think it will effect the performance after the first call

> In case we cant we probably need to think of another solution for that.

Not sure I follow, can you explain a bit more

**Comment by Cahllagerfeld** [comment]
I think I got a possible solution tonight. If that works we can reuse the Astra-Service to some extend but redefine it. I'll test it during the day!

**Comment by eddiejaoude** [comment]
Oh awesome! any questions or want to bounce ideas let me know. Today I am quite busy with conference talks and community calls etc, but tomorrow I have more time if you want to bounce ideas and/or pair on it 🤓

**Comment by Cahllagerfeld** [comment]
Seems like my idea works as I want 😄

**Comment by eddiejaoude** [comment]
Awesome 💥

**Comment by Cahllagerfeld** [comment]
We should discuss from where the namespace will come? Is it sent with a header, in the body, etc...?

**Comment by eddiejaoude** [comment]
Oh good question 🤔 

Probably header is best, what do you think?

**Comment by Cahllagerfeld** [comment]
My answer would have been header as well :D

**Comment by Cahllagerfeld** [comment]
I came up with a solution to handle the Multi-Tenancy I think!!

**Comment by eddiejaoude** [comment]
Great 👍

**Comment by Cahllagerfeld** [comment]
I think it's too complicated to explain in via comment properly. We could discuss it in the voice channel or when pairing on it.

**Comment by eddiejaoude** [comment]
Sure 👍 then we can document notes here afterwards and it will also include the community 🤓
