### ISSUE TITLE
[FEATURE] Emit Event via Websockets whenever a new Github Event is created

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#273]
# ⭐ Suggestion

For the interactive Map project, the API needs to be able to establish WebSocket connections

# Concept

## Requirements
- API needs to be able to act as a WebSocket server
- Whenever a new Event from Github is tracked, we need to emit the event + the profile data via WebSockets to the connected clients
- following events need to be tracked
    - `join` when a new client connects
    - `getAllPointers` from retrieving all locations
    - `createPointer` for creating a new pointer on the map
    
## Implementation
- Usage of [Nestjs-Socket-io](https://docs.nestjs.com/websockets/gateways) Implementation
- As it is a mix of HTTP-Request and Websocket [this Codesandbox](https://codesandbox.io/s/floral-water-fbqey) might come handy

## Things to discuss
- How should we configure CORS - Should we wildcard it, or only allow specific URLs to connect?
- How do we want to document the WS-API? From my research[[1](https://github.com/nestjs/nest/issues/1794)] that's not supported with Swagger and also not planned

**Comment by stemount** [comment]
> How should we configure CORS - Should we wildcard it, or only allow specific URLs to connect?

Is this solution only really required by `*.eddiehub.tld` for websockets? I think if it's only really useful for internal stuff then we should have a CORS/security policy for said domain.

As websockets are so lightweight by design (over a REST API), I would say opening it up to the world would be absolutely fine.

> How do we want to document the WS-API? From my research[https://github.com/nestjs/nest/issues/1794] that's not supported with Swagger and also not planned

This looks very promising. https://github.com/nestjs/swagger/issues/191#issuecomment-483326237
