### ISSUE TITLE
Authentication-Service

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#51]
Does this Api need to be protected by JWT using `passport` for example?

**Comment by eddiejaoude** [comment]
Great question 👍 

I think we will protect the API with an app token for written, then for reads have it public

**Comment by Cahllagerfeld** [comment]
I like this idea a lot to make reading public!

**Comment by eddiejaoude** [comment]
I think then people in the community can make their own apps to consume the data - we will not have a private data

**Comment by Cahllagerfeld** [comment]
Thats true. 
I'm not yet 100% sure which Auth-Flow will fit best for us in this scenario.
We dont have to authenticate users, so its probably m2m-Authentication. That could mean User-Credential-Flow, but im not sure if thats the right one for us.

**Comment by eddiejaoude** [comment]
Yep `m2m` authentication sounds good, but you are right there are multiple options. I think the simplest would work best here.

Is my token idea too simple...

- Environment variable collection (array) of tokens that are allowed write access
- Requests with a valid token in the header are given write access, otherwise invalid token response is sent back

Not sure if there is a library out there that does something like this already. I do not want to use a 3rd party service like OAuth though

**Comment by Cahllagerfeld** [comment]
These are exactly my thoughts Yikes :D
I think OAuth or even with Identity Provider like KeyCloak or Auth0 is overkill.

**Comment by eddiejaoude** [comment]
Also these providers are not good for automated testing or offline development - I had too many bad experiences in the past

**Comment by Cahllagerfeld** [comment]
I started implementing AuthGuards for this as nest proposes them for authentication.
I suggest using a Guard for Discord and one for Github.
This way we can better control the accesses from the Apps. Scenarios like Endpoints that only a GithubAction can access or vice versa are easily implementable then.
